title: The Elegant Canvas
tagline: painting with everything
email: andrada.morosan@manabreakstudios.com
description: >
  Personal home of Andrada Morosan
baseurl: ""
url: ""
paginate:         1

# About/contact
author:
  name:              Andrada Morosan
  url:               https://andrachan.github.io
  email:             andrada.morosan@manabreakstudios.com

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
